services:
  # Zookeeper（Kafka 依赖）
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - data_net

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
    volumes:
      - mongo_data:/data/db
    networks:
      - data_net

  # Kafka
  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,INTERNAL://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,INTERNAL://kafka:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    networks:
      - data_net

  # ClickHouse
  clickhouse:
    image: clickhouse:latest
    container_name: clickhouse
    ports:
      - "8123:8123"   # HTTP
      - "9000:9000"   # Native
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    environment:
      CLICKHOUSE_DB: dw_ods
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: mypassword
    networks:
      - data_net

  # Redis
  redis:
    image: redis:alpine3.22
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    entrypoint: ["docker-entrypoint.sh"]
    command: ["redis-server"]
    networks:
      - data_net

  # Flink JobManager
  jobmanager:
    image: apache/flink:1.19.1-java17
    container_name: flink-jobmanager
    platform: linux/amd64
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
    ports:
      - "8081:8081"
    command: jobmanager
    depends_on:
      - kafka
      - clickhouse
      - redis
    networks:
      - data_net

  # Flink TaskManager
  taskmanager:
    image: apache/flink:1.19.1-java17
    container_name: flink-taskmanager
    platform: linux/amd64
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
    depends_on:
      - jobmanager
      - clickhouse
      - redis
    command: taskmanager
    networks:
      - data_net

volumes:
  clickhouse_data:
  redis_data:
  mongo_data:
