server.port=8081

spring.data.mongodb.uri=${MONGO_URI:mongodb://mongo:27017/imageurl}

management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.prometheus.enabled=true
management.prometheus.metrics.export.enabled=true
management.health.elasticsearch.enabled=false

feature.redis.enabled=false
feature.kafka.enabled=false
feature.elasticsearch.enabled=false

spring.autoconfigure.exclude=\
org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration,\
org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration,\
org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration
