spring.application.name=worker1
server.port=8081
spring.data.mongodb.uri=mongodb://localhost:27017/imageurl?replicaSet=rs0
#spring.data.mongodb.uri=mongodb://milailai:milailaimiduoduo1@192.3.163.178:27017/imageurl?authSource=admin

# ??????????????
lucene.index.path=./luceneIndex


#logging.file.name=/app/logs/springboot.log
logging.level.org.springframework=INFO

management.endpoints.web.exposure.include=*

# Prometheus ??? metrics
management.endpoint.prometheus.enabled=true

# ?????????
management.prometheus.metrics.export.enabled=true

# ??????????????
management.metrics.enable.all=true
spring.devtools.restart.enabled=false
logging.level.io.micrometer.core.instrument=DEBUG


spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.timeout=2000
spring.data.redis.repositories.enabled=false

spring.elasticsearch.uris=http://localhost:9200


# Elasticsearch ??
es.host=127.0.0.1
es.port=9200

#spring.kafka.bootstrap-servers= localhost:9092
#spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
#spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer


# Kafka ??
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.acks=1
spring.kafka.producer.retries=3
